Homework2
made-ml-in-prod-2021/Ilya2567 pull request #3
Opened 2021-05-19 11:21 UTC by Ilya2567

Самооценка

(1) Оберните inference вашей модели в rest сервис.
Баллы: +3 балла

(3) Напишите скрипт, который будет делать запросы к вашему сервису.
Баллы: +2 балла

(4) Сделайте валидацию входных данных.
Баллы: +3 балла

(5) Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run).
Баллы: +4 балла

(6) Оптимизируйте размер docker image.

Использовал slim версию питона (1.38G -> 607M)
Создал отдельный файл requirements_docker.txt, с меньшим количеством пакетов
Создал файл .dockerignore, чтобы исключить копирование служебных файлов PyCharm

Баллы: +3 балла

(7) опубликуйте образ в https://hub.docker.com/.
Команды указаны выше.
Баллы: +2 балла

(8) напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель.
Команды указаны выше.
Баллы: +1 балл

(5) проведите самооценку.
Баллы: +1 балл

Итого: 19 баллов

2021-05-19 19:52 UTC, LKudrenok approved these changes
В целом все написано красиво и чисто, разве что можно было поудалять закомменченный ненужный код (например, в файле build_features.py), раз уж предполагается, что это production-ready код.
Сделано всё, кроме тестов, поэтому согласна с самооценкой автора в 19 баллов.

2021-05-23 12:53 UTC, Mikhail-M requested changes
в реквесте есть код первой дз, добейтесь, чтобы не было

2021-05-26 08:31 UTC, Ilya2567 commented
> в реквесте есть код первой дз, добейтесь, чтобы не было

Смержил в веткой main, конфликты зарезолвил.

2021-05-27 08:41 UTC, Mikhail-M approved these changes
Валидация: 2 балла, все круто, но проверок бы побольше разных
Оптимизация: 2 балла

Баллы: 17

2021-05-27 11:33 UTC, merged